import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillGitlab } from "react-icons/ai";
import {
  SiTypescript,
  SiNextdotjs,
  SiSass,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiRedux,
  SiMongodb,
  SiExpress,
  SiTailwindcss,
} from "react-icons/si";
import { RiReactjsFill } from "react-icons/ri";
import Image from "next/image";
import avatar from "../public/avatar.png";
import code from "../public/code.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alan Rutyna Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-2xl font-burtons">Alan Rutyna</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Alan Rutyna
            </h2>
            <h3 className="text-2xl py-2">Junior React Front-End Developer</h3>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-gray-800">
            <AiFillGithub />
            <AiFillGitlab />
          </div>
          <div className=" relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden">
            <Image alt="avatar" src={avatar} fill objectFit="cover" />
          </div>
        </section>
        <section>
          <div className=" flex flex-col justify-center items-center py-10">
            <div>
              <Image alt="code icon" src={code} width={100} height={100} />
            </div>
            <h3 className="text-2xl py-1">Technologies which i use:</h3>
            <ul className=" flex flex-col py-2 gap-4 leading-8 text-gray-800">
              <li className=" flex justify-center items-center gap-1">
                <p className="flex justify-center items-center">
                  <SiCss3 />
                  <SiHtml5 />
                  <SiJavascript />
                </p>
                <p className=" break-keep">HTML&nbsp;CSS&nbsp;JavaScript</p>
              </li>
              <li className=" flex justify-center gap-1 items-center">
                <RiReactjsFill />
                <SiNextdotjs />
                <SiRedux /> ReactJS&nbsp;Redux&nbsp;NextJS
              </li>
              <li className=" flex justify-center gap-1 items-center">
                <SiTypescript /> TypeScript
              </li>
              <li className=" flex justify-center gap-1 items-center">
                <SiSass />
                <SiTailwindcss /> Sass&nbsp;+&nbsp;Tailwind
              </li>
              <li className=" flex justify-center gap-1 items-center">
                <SiMongodb />
                <SiExpress /> ExpressJS+MongoDB
              </li>
            </ul>
          </div>
        </section>
      </main>
    </>
  );
}
